"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'audi'? I predict False.");
console.log(car == 'audi');
console.log("Is car != 'bmw'? I predict True.");
console.log(car != 'bmw');
console.log("Is car === 'Subaru'? I predict False.");
console.log(car === 'Subaru');
console.log("Is car !== 'toyota'? I predict True.");
console.log(car !== 'toyota');
console.log("Is car.toUpperCase() == 'SUBARU'? I predict false.");
console.log(car.toUpperCase() == 'TOYOTA');
console.log("Is car.length == 6? I predict True.");
console.log(car.length == 6);
console.log("Is car.length > 3? I predict True.");
console.log(car.length > 3);
console.log("Is car.length < 3? I predict False.");
console.log(car.length < 3);
console.log("Is car.includes('u')? I predict False.");
console.log(car.includes('y'));
