"use strict";
let mountains = ["Nanga Parbat", "Karakoram", "Himalayas", "Margalla Hills"];
console.log("List of mountains:", mountains);
let rivers = ["Indus river", "Jhelum river", "Chenab river", "Ravi river"];
console.log("List of rivers:", rivers);
let countries = ["Pakistan", "India", "Afganistan", "Nepal", "Bangladesh"];
console.log("List of countries:", countries);
let cities = ["Karachi", "Lahore", "Islamabad", "Sukkur"];
console.log("List of cities:", cities);
let languages = ["Sindhi", "Urdu", "Punjabi", "Siraiki", "Pashto", "Balochi"];
console.log("List of languages:", languages);
